hl.on("hyprland.start", function()
    hl.exec_cmd("mako")
    hl.exec_cmd("waybar")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("ags run ~/.config/ags/app.ts")
    hl.exec_cmd("hyprpaper & ~/.config/hypr/scripts/random-wallpaper.sh")
end)
